# SPDX-License-Identifier: PMPL-1.0-or-later
# Data export — CSV, JSON, and report generation.

"""
    export_csv(data::Dict, filepath::String) -> Dict

Export analysis results to CSV format.
"""
function export_csv(data::Dict, filepath::String)
    try
        # Flatten dict to key-value pairs
        rows = [(string(k), _format_cell(v)) for (k, v) in data
                if !(v isa Dict || v isa Vector)]

        open(filepath, "w") do io
            println(io, "statistic,value")
            for (k, v) in rows
                println(io, "\"$k\",\"$v\"")
            end
        end

        return Dict{String,Any}(
            "status" => "success",
            "filepath" => filepath,
            "n_rows" => length(rows)
        )
    catch e
        return Dict{String,Any}("error" => "Export failed: $(string(e))")
    end
end

"""
    export_json(data::Dict, filepath::String) -> Dict

Export analysis results to JSON format.
"""
function export_json(data::Dict, filepath::String)
    try
        open(filepath, "w") do io
            JSON3.pretty(io, data)
        end

        return Dict{String,Any}(
            "status" => "success",
            "filepath" => filepath
        )
    catch e
        return Dict{String,Any}("error" => "Export failed: $(string(e))")
    end
end

"""
    generate_report(results::Vector{Dict}; title="") -> String

Generate a text report from multiple analysis results.
"""
function generate_report(results::Vector{Dict}; title::String="Statistical Report")
    lines = String[]
    push!(lines, "=" ^ 72)
    push!(lines, "  $title")
    push!(lines, "  Generated: $(Dates.format(now(), "yyyy-mm-dd HH:MM:SS"))")
    push!(lines, "=" ^ 72)
    push!(lines, "")
    push!(lines, "  NOTE: All statistics computed by verified Julia functions.")
    push!(lines, "  No numbers were generated by neural inference.")
    push!(lines, "")

    for (i, result) in enumerate(results)
        push!(lines, "-" ^ 72)
        push!(lines, "  Section $i")
        push!(lines, "-" ^ 72)

        for (k, v) in sort(collect(result), by=first)
            if v isa Dict || v isa Vector
                continue
            end
            push!(lines, "  $(rpad(k, 30)) $(v)")
        end
        push!(lines, "")
    end

    push!(lines, "=" ^ 72)
    push!(lines, "  End of Report")
    push!(lines, "=" ^ 72)

    return join(lines, "\n")
end
