# SPDX-License-Identifier: MPL-2.0
# Tool definitions for LM Studio function calling.
# These definitions tell the LLM what symbolic tools are available.
# The LLM NEVER performs calculations — it requests tool calls,
# and StatistEase executes verified Julia code.

function get_tools()
    return Dict{String,Any}[
        _tool("descriptive_statistics",
              "Calculate comprehensive descriptive statistics: mean, median, mode, SD, skewness, kurtosis, quartiles, confidence intervals, and normality hints.",
              Dict("data" => Dict("type"=>"array", "description"=>"Numeric data vector")),
              ["data"]),
        _tool("frequency_analysis",
              "Create frequency table for categorical data with relative and cumulative frequencies.",
              Dict("data" => Dict("type"=>"array", "description"=>"Categorical data as string array")),
              ["data"]),
        _tool("t_test",
              "Perform t-tests: independent (Welch's), paired, or one-sample. Includes Cohen's d effect size.",
              Dict("type" => Dict("type"=>"string", "enum"=>["independent","paired","one_sample"], "description"=>"Type of t-test"),
                   "group1" => Dict("type"=>"array", "description"=>"First group / data"),
                   "group2" => Dict("type"=>"array", "description"=>"Second group (independent/paired)"),
                   "mu0" => Dict("type"=>"number", "description"=>"Hypothesized mean (one-sample)"),
                   "alpha" => Dict("type"=>"number", "description"=>"Significance level (default 0.05)")),
              ["type", "group1"]),
        _tool("anova",
              "Perform one-way ANOVA with eta-squared and omega-squared effect sizes.",
              Dict("groups" => Dict("type"=>"array", "description"=>"Array of group data arrays")),
              ["groups"]),
        _tool("chi_square",
              "Chi-square test of independence or goodness-of-fit. Includes Cramer's V effect size.",
              Dict("type" => Dict("type"=>"string", "enum"=>["independence","goodness_of_fit"], "description"=>"Test type"),
                   "observed" => Dict("type"=>"array", "description"=>"Observed frequencies"),
                   "expected_proportions" => Dict("type"=>"array", "description"=>"Expected proportions (GoF only)")),
              ["type", "observed"]),
        _tool("correlation",
              "Calculate Pearson or Spearman correlation with significance testing and confidence intervals.",
              Dict("x" => Dict("type"=>"array", "description"=>"First variable"),
                   "y" => Dict("type"=>"array", "description"=>"Second variable"),
                   "method" => Dict("type"=>"string", "enum"=>["pearson","spearman"], "description"=>"Correlation method")),
              ["x", "y"]),
        _tool("regression",
              "Perform simple or multiple linear regression with ANOVA table, VIF, and diagnostics.",
              Dict("x" => Dict("type"=>"array", "description"=>"Predictor(s)"),
                   "y" => Dict("type"=>"array", "description"=>"Outcome variable"),
                   "var_names" => Dict("type"=>"array", "description"=>"Predictor names (optional)")),
              ["x", "y"]),
        _tool("nonparametric_test",
              "Non-parametric tests: Mann-Whitney U, Wilcoxon signed-rank, or Kruskal-Wallis H.",
              Dict("type" => Dict("type"=>"string", "enum"=>["mann_whitney","wilcoxon","kruskal_wallis"], "description"=>"Test type"),
                   "group1" => Dict("type"=>"array", "description"=>"First group"),
                   "group2" => Dict("type"=>"array", "description"=>"Second group"),
                   "groups" => Dict("type"=>"array", "description"=>"Array of groups (Kruskal-Wallis)")),
              ["type"]),
        _tool("permanova",
              "PERMANOVA: Permutational Multivariate Analysis of Variance. Tests whether group centroids differ in multivariate space using a distance matrix and permutation-based significance testing. Non-parametric — does not assume multivariate normality.",
              Dict("distance_matrix" => Dict("type"=>"array", "description"=>"Symmetric distance matrix (array of arrays, e.g. Euclidean or Bray-Curtis distances)"),
                   "group_labels" => Dict("type"=>"array", "description"=>"Group label for each observation (same length as matrix dimension)"),
                   "n_permutations" => Dict("type"=>"integer", "description"=>"Number of permutations (default 999)"),
                   "alpha" => Dict("type"=>"number", "description"=>"Significance level (default 0.05)")),
              ["distance_matrix", "group_labels"]),
        _tool("effect_size_calculator",
              "Calculate and convert between effect sizes: Cohen's d, r, eta-squared, odds ratio, Hedges' g.",
              Dict("cohens_d" => Dict("type"=>"number", "description"=>"Cohen's d"),
                   "r" => Dict("type"=>"number", "description"=>"Correlation coefficient"),
                   "eta_squared" => Dict("type"=>"number", "description"=>"Eta-squared"),
                   "odds_ratio" => Dict("type"=>"number", "description"=>"Odds ratio"),
                   "n1" => Dict("type"=>"integer", "description"=>"Group 1 size"),
                   "n2" => Dict("type"=>"integer", "description"=>"Group 2 size")),
              String[]),
        _tool("power_analysis",
              "Power analysis: calculate required sample size or achieved power for t-tests.",
              Dict("effect_size" => Dict("type"=>"number", "description"=>"Expected effect size (Cohen's d)"),
                   "n" => Dict("type"=>"integer", "description"=>"Sample size per group"),
                   "alpha" => Dict("type"=>"number", "description"=>"Significance level"),
                   "power" => Dict("type"=>"number", "description"=>"Desired power")),
              ["effect_size"]),
        _tool("sample_size_calculator",
              "Calculate required sample size for means, proportions, correlation, regression, or ANOVA designs.",
              Dict("design" => Dict("type"=>"string", "enum"=>["means","proportions","correlation","regression","anova"], "description"=>"Study design"),
                   "effect_size" => Dict("type"=>"number", "description"=>"Expected effect size"),
                   "alpha" => Dict("type"=>"number", "description"=>"Significance level"),
                   "power" => Dict("type"=>"number", "description"=>"Desired power"),
                   "n_groups" => Dict("type"=>"integer", "description"=>"Groups (ANOVA)"),
                   "n_predictors" => Dict("type"=>"integer", "description"=>"Predictors (regression)")),
              ["design", "effect_size"]),
        _tool("test_assumptions",
              "Test statistical assumptions: normality (Jarque-Bera, KS) and homogeneity of variance (Levene's).",
              Dict("type" => Dict("type"=>"string", "enum"=>["normality","levene"], "description"=>"Assumption to test"),
                   "data" => Dict("type"=>"array", "description"=>"Data vector (normality)"),
                   "groups" => Dict("type"=>"array", "description"=>"Groups (Levene's)")),
              ["type"]),
        _tool("bayesian_analysis",
              "Perform Bayesian updating of prior beliefs with new evidence.",
              Dict("prior" => Dict("type"=>"array", "description"=>"Prior probabilities"),
                   "likelihood" => Dict("type"=>"array", "description"=>"Likelihood matrix"),
                   "data_index" => Dict("type"=>"integer", "description"=>"Observed data index")),
              ["prior", "likelihood", "data_index"]),
        _tool("bayes_factor",
              "Calculate Bayes Factor (BIC approximation) comparing two nested models.",
              Dict("r_squared_full" => Dict("type"=>"number", "description"=>"R-squared of full model"),
                   "r_squared_reduced" => Dict("type"=>"number", "description"=>"R-squared of reduced model"),
                   "n" => Dict("type"=>"integer", "description"=>"Sample size"),
                   "p_full" => Dict("type"=>"integer", "description"=>"Parameters in full model"),
                   "p_reduced" => Dict("type"=>"integer", "description"=>"Parameters in reduced model")),
              ["r_squared_full", "r_squared_reduced", "n", "p_full", "p_reduced"]),
        _tool("credible_intervals",
              "Calculate Bayesian credible intervals (ETI and HDI) from posterior samples.",
              Dict("samples" => Dict("type"=>"array", "description"=>"Posterior samples"),
                   "level" => Dict("type"=>"number", "description"=>"Credible level (default 0.95)")),
              ["samples"]),
        _tool("fuzzy_logic_analysis",
              "Perform fuzzy logic membership calculations.",
              Dict("value" => Dict("type"=>"number", "description"=>"Value to evaluate"),
                   "center" => Dict("type"=>"number", "description"=>"Center of fuzzy set"),
                   "width" => Dict("type"=>"number", "description"=>"Width of fuzzy set"),
                   "operation" => Dict("type"=>"string", "enum"=>["membership","and","or"], "description"=>"Operation")),
              ["value", "center", "width", "operation"]),
        _tool("dempster_shafer",
              "Combine evidence using Dempster-Shafer theory of evidence.",
              Dict("evidence1" => Dict("type"=>"object", "description"=>"First mass function"),
                   "evidence2" => Dict("type"=>"object", "description"=>"Second mass function")),
              ["evidence1", "evidence2"]),
        _tool("granger_causality",
              "Test for Granger causality between two time series.",
              Dict("series_x" => Dict("type"=>"array", "description"=>"Potential cause series"),
                   "series_y" => Dict("type"=>"array", "description"=>"Potential effect series"),
                   "lag" => Dict("type"=>"integer", "description"=>"Number of lags")),
              ["series_x", "series_y"]),
        _tool("james_stein",
              "Apply James-Stein shrinkage estimator for improved parameter estimation.",
              Dict("observations" => Dict("type"=>"array", "description"=>"Observations"),
                   "grand_mean" => Dict("type"=>"number", "description"=>"Optional grand mean")),
              ["observations"]),
        _tool("diagnostic_metrics",
              "Calculate sensitivity, specificity, PPV, NPV, and accuracy.",
              Dict("true_positive" => Dict("type"=>"integer", "description"=>"True positives"),
                   "false_negative" => Dict("type"=>"integer", "description"=>"False negatives"),
                   "true_negative" => Dict("type"=>"integer", "description"=>"True negatives"),
                   "false_positive" => Dict("type"=>"integer", "description"=>"False positives")),
              ["true_positive", "false_negative", "true_negative", "false_positive"]),
        _tool("reliability_analysis",
              "Calculate Cronbach's Alpha reliability from item response data.",
              Dict("items" => Dict("type"=>"array", "description"=>"Matrix [rows=subjects, cols=items]")),
              ["items"]),
        _tool("measurement_analysis",
              "Advanced measurement: McDonald's Omega, SEM, item analysis.",
              Dict("type" => Dict("type"=>"string", "enum"=>["omega","sem","item_analysis"], "description"=>"Analysis type"),
                   "items" => Dict("type"=>"array", "description"=>"Item response matrix"),
                   "reliability" => Dict("type"=>"number", "description"=>"Reliability (for SEM)"),
                   "sd" => Dict("type"=>"number", "description"=>"SD (for SEM)")),
              ["type"]),
        _tool("validity_assessment",
              "Assess content validity using Content Validity Ratio (CVR).",
              Dict("n_essential" => Dict("type"=>"integer", "description"=>"Panelists rating essential"),
                   "n_total" => Dict("type"=>"integer", "description"=>"Total panelists")),
              ["n_essential", "n_total"]),
        _tool("criterion_validity_test",
              "Assess concurrent or predictive criterion validity.",
              Dict("predictor" => Dict("type"=>"array", "description"=>"Predictor scores"),
                   "criterion" => Dict("type"=>"array", "description"=>"Criterion scores"),
                   "validity_type" => Dict("type"=>"string", "enum"=>["concurrent","predictive"], "description"=>"Validity type")),
              ["predictor", "criterion"]),
        _tool("inter_rater_reliability",
              "Calculate inter-rater reliability: Cohen's Kappa, Fleiss' Kappa, or ICC.",
              Dict("type" => Dict("type"=>"string", "enum"=>["cohens_kappa","fleiss_kappa","icc"], "description"=>"Measure"),
                   "rater1" => Dict("type"=>"array", "description"=>"Rater 1 ratings (Cohen's)"),
                   "rater2" => Dict("type"=>"array", "description"=>"Rater 2 ratings (Cohen's)"),
                   "ratings_matrix" => Dict("type"=>"array", "description"=>"Ratings matrix (Fleiss/ICC)"),
                   "icc_type" => Dict("type"=>"string", "description"=>"ICC type")),
              ["type"]),
        _tool("qualitative_analysis",
              "Qualitative research support: thematic saturation estimation.",
              Dict("themes_per_interview" => Dict("type"=>"array", "description"=>"New themes per interview"),
                   "window" => Dict("type"=>"integer", "description"=>"Moving average window")),
              ["themes_per_interview"]),
        _tool("calculate_pre",
              "Calculate Proportional Reduction in Error (PRE) and R-squared.",
              Dict("observed" => Dict("type"=>"array", "description"=>"Observed values"),
                   "predicted" => Dict("type"=>"array", "description"=>"Predicted values"),
                   "baseline" => Dict("type"=>"array", "description"=>"Baseline predictions (optional)")),
              ["observed", "predicted"]),
        _tool("sampling_design",
              "Calculate design effects, margin of error, or finite population corrections.",
              Dict("type" => Dict("type"=>"string", "enum"=>["design_effect","margin_of_error"], "description"=>"Calculation type"),
                   "icc" => Dict("type"=>"number", "description"=>"ICC for design effect"),
                   "cluster_size" => Dict("type"=>"integer", "description"=>"Cluster size"),
                   "n" => Dict("type"=>"integer", "description"=>"Sample size"),
                   "proportion" => Dict("type"=>"number", "description"=>"Estimated proportion"),
                   "confidence" => Dict("type"=>"number", "description"=>"Confidence level"),
                   "population" => Dict("type"=>"integer", "description"=>"Population size")),
              ["type"]),
    ]
end

# Helper to create tool definitions without repetition
function _tool(name::String, description::String, properties::Dict, required::Vector{String})
    return Dict{String,Any}(
        "type" => "function",
        "function" => Dict{String,Any}(
            "name" => name,
            "description" => description,
            "parameters" => Dict{String,Any}(
                "type" => "object",
                "properties" => Dict{String,Any}(properties...),
                "required" => required
            )
        )
    )
end
